### ISSUE TITLE
Back command teleports into blocks.

### ISSUE THREAD

**Issue by Glassmaker** [CandiceJoy/PerUserDifficulty#5]
When I tried /back to return to death point I was teleported into block below the death point.

Maybe add a check if there is a safe place where player going to be teleported to like if the block is air.

**Comment by CandiceJoy** [comment]
How should this work exactly as far as the algorithm for finding the spot?  Also, what should happen if there isn't a safe spot?

**Comment by Glassmaker** [comment]
here is one way of doing it:
- Check the spot of teleportation is 2 air blocks high, if not check if there is a valid spot in 16 x 16 x 16 cube, the centre point is initial teleportation coordinates.
- if 2 air blocks were found, check if the block below them is safe block, example it shouldn't be lava, cactus or void
- if there wasn't valid place to send the player to display a message that the teleport to place is blocked.

**Comment by CandiceJoy** [comment]
This doesn't really work across dimensions because the dimension/area may not be loaded where the player is teleporting (maybe for same-dimension teleports the area may not be loaded also?) to so I can't check it for these things.  What should I do?  A few things I've come up with are:

1) Simply don't do any checking for cross-dimensional transports
2) Teleport the player to the target dimension first, then do the checking and teleport if necessary.  This may need to add a back location and we may have to find a sane spot in the new dimension for the player to be.
3) Some sort of trickery to do the checking anyway or do the checking a different way that will work.

I've implemented the check but I'm not going to push to github because it's got some odd functionality until I decide what to do with cross-dimensional teleports.  Specifically, it will check for spots and adjust it accordingly in the player's current dimension, even if it's doing a cross dimensional teleport.  This will be fixed once I know what to do with cross-dim teleports.

**Comment by Glassmaker** [comment]
You can go with solution no. 2, it's the most effective one.

**Comment by CandiceJoy** [comment]
I came up with a modified version of 2.  It'll teleport you to the new dimension, then try to find a proper location in that dimension.  If it fails, it'll teleport you back to where you were originally.  :)
